const COMMENTS_GET = 'COMMENTS_GET';
const COMMENTS_GET_REQUEST = 'COMMENTS_GET_REQUEST';
const COMMENTS_GET_SUCCESS = 'COMMENTS_GET_SUCCESS';
const COMMENTS_GET_FAILURE = 'COMMENTS_GET_FAILURE';

export {
    COMMENTS_GET,
    COMMENTS_GET_FAILURE,
    COMMENTS_GET_SUCCESS,
    COMMENTS_GET_REQUEST,
}