const COMMENTS_GET = 'COMMENTS_GET';
const COMMENTS_GET_REQUEST = 'COMMENTS_GET_REQUEST';
const COMMENTS_GET_SUCCESS = 'COMMENTS_GET_SUCCESS';
const COMMENTS_GET_FAILURE = 'COMMENTS_GET_FAILURE';

const COMMENTS_POST = 'COMMENTS_POST';
const COMMENTS_POST_REQUEST = 'COMMENTS_POST_REQUEST';
const COMMENTS_POST_SUCCESS = 'COMMENTS_POST_SUCCESS';
const COMMENTS_POST_FAILURE = 'COMMENTS_POST_FAILURE';

export {
    COMMENTS_GET,
    COMMENTS_GET_FAILURE,
    COMMENTS_GET_SUCCESS,
    COMMENTS_GET_REQUEST,
    COMMENTS_POST,
    COMMENTS_POST_REQUEST,
    COMMENTS_POST_SUCCESS,
    COMMENTS_POST_FAILURE,
}